spring:
  data:
    web:
      pageable:
        page-parameter: page
        size-parameter: size
        one-indexed-parameters: true
  profiles:
    active: dev
  mvc:
    # \u51FA\u73B0\u9519\u8BEF\u65F6\u76F4\u63A5\u629B\u51FA\u5F02\u5E38
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

